### ISSUE TITLE
Career fields confusing (and sexist) - nurse

### ISSUE THREAD

**Issue by rebecca-mccann** [yalla-coop/erica-playground#36]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Backlog / New idea

### Priority

Low

### Please describe your issue & include screenshots:

There are loads of options within 'Nurse' as a career option, and many of them overlap. Is there a way to streamline so we don't open ourselves up to loads of questions? I wouldn't even know what to put my Mum in! Also why do you have to be male to be a chief nurse?! Rebecca MC

![image](https://github.com/yalla-coop/smf-app-QA-repo/assets/142805793/51562e68-a2b6-4bcf-8ce4-c4028601a6de)

### Page URL

https://smf-web-app.herokuapp.com/

**Comment by egasparini** [comment]
Great point @rebecca-mccann! 
That looks bad indeed... we are pulling the list of jobs from the Office for National Statistics, so it's unfortunately an officia list... @Wah-AuSMF I leave this to you to review and let us know next steps. 
Thanks!

**Comment by Wah-AuSMF** [comment]
Thanks both!

@egasparini I've discussed internally. @dupreesi, please: 

- [x] Change title from 'Nurse, male, chief' to '**Nurse, chief'**

I've also searched the [official SOC code list](https://github.com/ONSdigital/dp-classification-tools/blob/develop/standard-occupational-classification/data/jobrecords.txt) to find other job titles which may be seen as problematic. There are no other job titles which stipulate male (or "female") but there are titles which are _not_ gender-neutral e.g. it lists "Chairman" instead of "Chairperson". 

Having discussed this internally, this is far from ideal but the decision, for now, is that we're not going to deviate too much from the ONS list - since that will cause other issues. However, we will definitely bear this in mind going forward. For now, @dupreesi, please remove 'male' from the nurse title as above.

**Comment by dupreesi** [comment]
done @Wah-AuSMF will be deployed tomorrow
